name: Validate

on:
  push:
    paths:
    - mls.json
    - mls_schema.json
  pull_request:
    paths:
    - mls.json
    - mls_schema.json

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema
    - name: Validate mls.json
      run: |
        jsonschema -i mls.json mls_schema.json
    - name: Check that mls.json is sorted
      run: |
        diff -u mls.json <(jq -S <mls.json)
